server:
  port: 8080
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080/admin
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"